/*
Script de criação do esquema relacional
*/


-- Entidade Pessoa
CREATE TABLE Pessoa (
    CPF VARCHAR(11) PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
);

-- Atributo Telefones Multivalorado de Pessoa
CREATE TABLE ContatoTelefones (
    CPF VARCHAR(11) NOT NULL,
    Telefone VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ContatoTelefones PRIMARY KEY (CPF, Telefone),
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF) ON DELETE CASCADE ON UPDATE RESTRICT
);

-- Atributo Emails Multivalorado de Pessoa
CREATE TABLE ContatoEmails (
    CPF VARCHAR(11) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ContatoEmails PRIMARY KEY (CPF, Email),
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF) ON DELETE CASCADE ON UPDATE RESTRICT
);

-- Entidade PessoaLGBT
CREATE TABLE PessoaLGBT (
    CPF VARCHAR(11) PRIMARY KEY,
    NomeSocial VARCHAR(255) NOT NULL,
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF) ON DELETE CASCADE ON UPDATE RESTRICT
);

-- Entidade Servidor
CREATE TABLE Servidor (
    CPF VARCHAR(11) PRIMARY KEY,
    TipoDeContrato VARCHAR(100) NOT NULL,
    CodigoDepartamento INT NOT NULL,
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (CodigoDepartamento) REFERENCES Departamento(Codigo) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Entidade Docente
CREATE TABLE Docente (
    CPF VARCHAR(11) PRIMARY KEY,
    SIAPE VARCHAR(8) NOT NULL,
    ID_PCD INT,
    FOREIGN KEY (CPF) REFERENCES Servidor(CPF) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (ID_PCD) REFERENCES PCD(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Entidade Técnico Administrativo
CREATE TABLE TecnicoAdministrativo(
    CPF VARCHAR(11) PRIMARY KEY,
    SIAPE VARCHAR(8) NOT NULL UNIQUE,
    ID_MEMBRO INT,
    ID_PCD INT,
    ID_CARGO INT,
    FOREIGN KEY (CPF) REFERENCES Servidor(CPF) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (ID_MEMBRO) REFERENCES MembroDaEquipe(ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_PCD) REFERENCES PCD(ID_PCD) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO) ON DELETE RESTRICT ON UPDATE CASCADE,
);

-- Entidade Terceirizado
CREATE TABLE Terceirizado(
    CPF VARCHAR(11) PRIMARY KEY,
    ID_MEMBRO INT,
    ID_CARGO INT,
    FOREIGN KEY (CPF) REFERENCES Servidor(CPF) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (ID_MEMBRO) REFERENCES MembroDaEquipe(ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_CARGO) REFERENCES Cargo(ID_CARGO) ON DELETE RESTRICT ON UPDATE CASCADE,
);

-- Entidade Aluno
CREATE TABLE Aluno (
    CPF VARCHAR(11) PRIMARY KEY,
    Matricula VARCHAR(9) NOT NULL,
    ID_MEMBRO INT,
    ID_PCD INT,
    FOREIGN KEY (CPF) REFERENCES Pessoa(CPF) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (ID_MEMBRO) REFERENCES MembroDaEquipe(ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_PCD) REFERENCES PCD(ID_PCD) ON DELETE RESTRICT ON UPDATE CASCADE,
);

-- Entidade Membro da Equipe
CREATE TABLE MembroDaEquipe(
    ID_MEMBRO INT PRIMARY KEY AUTO_INCREMENT,
    RegimeDeTrabalho VARCHAR(100) NOT NULL,
    ID_COORDENADOR INT,
    FOREIGN KEY (ID_COORDENADOR) REFERENCES MembroDaEquipe(ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE,
);

-- Atributo Período de Vínculo Multivalorado de Membro da Equipe
CREATE TABLE PeriodoDeVinculo(
    DataDeInicio DATE NOT NULL,
    DataDeFim DATE NOT NULL,
    ID_MEMBRO INT NOT NULL,
    FOREIGN KEY (ID_MEMBRO) REFERENCES MembroDaEquipe(ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ID_PERIODO PRIMARY KEY (ID_MEMBRO, DataDeInicio, DataDeFim),
);

-- Entidade Bolsista
CREATE TABLE Bolsista(
    ID_BOLSISTA INT PRIMARY KEY,
    Salario MONEY NOT NULL,
    FOREIGN KEY (ID_BOLSISTA) REFERENCES MembroDaEquipe(ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Entidade Bolsista de Produção
CREATE TABLE BolsistaProducao(
    ID_BOLSISTA INT PRIMARY KEY,
    FOREIGN KEY (ID_BOLSISTA) REFERENCES Bolsista(ID_BOLSISTA) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Entidade Bolsista de Inclusão
CREATE TABLE Bolsista_Inclusao(
    ID_Bolsista INT PRIMARY KEY NOT NULL,
    FOREIGN KEY (ID_Bolsista) REFERENCES Bolsista(ID_Membro) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Atributo Relatórios Multivalorado do Bolsista de Inclusão
CREATE TABLE Relatorios(
    ID_BOLSISTA INT NOT NULL,
    DataReferente DATE NOT NULL,
    Relatorios_Semanais VARCHAR(1000),
    FOREIGN KEY (ID_BOLSISTA) REFERENCES Bolsista_Inclusao(ID_BOLSISTA) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ID_RELATORIO PRIMARY KEY (ID_BOLSISTA, DataReferente)
);

-- Atributo Horários Multivalorado do Bolsista de Inclusão
CREATE TABLE Horarios(
    ID_HORARIOS INT PRIMARY KEY,
    Horarios_Monitoria DATE,
    FOREIGN KEY (ID_HORARIOS) REFERENCES Bolsista_Producao(ID_BOLSISTA) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Entidade Estagiário
CREATE TABLE Estagiário{
	ID_ESTAGIARIO INT PRIMARY KEY NOT NULL;
	Salario MONEY NOT NULL,
	CargaHoraria INT, 
	FOREIGN KEY (ID_ESTAGIARIO) REFERENCES MembroDeEqyuipe (ID_MEMBRO) ON DELETE RESTRICT ON UPDATE CASCADE
};

-- Entidade PCD
CREATE TABLE PCD {
	ID_PCD INT PRIMARY KEY AUTO_INCREMENT, 
};

-- Entidade Deficiência
CREATE TABLE Deficiencia(
    ID_DEFICIENCIA INT PRIMARY KEY,
    Categoria VARCHAR(50) NOT NULL,
);

-- Entidade Ação
CREATE TABLE Acao(
    ID_ACAO INT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL
    Descricao VARCHAR(500),
);

-- ################ NÃO REVISADO ################
-- Entidade Tecnologia
CREATE TABLE Tecnologia(
    ID_TECNOLOGIA INT PRIMARY KEY,
    Modelo VARCHAR(50) NOT NULL,
    N_Serie INT NOT NULL,
    Localizacao VARCHAR(100),
    ID_Categoria INT NOT NULL,

    FOREIGN KEY (ID_Categoria) REFERENCES Categoria_Tecnologia(ID_CATEGORIA) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Entidade Categoria Tecnologia
CREATE TABLE Categoria_Tecnologia(
    ID_CATEGORIA INT PRIMARY KEY,
    Tipo_Categoria VARCHAR(50) NOT NULL
);

-- Entidade Categoria Material
CREATE TABLE CategoriaMaterial(
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    TipoMaterial VARCHAR(100) NOT NULL,
);

-- Entidade Material Acessível
CREATE TABLE MaterialAcessivel(
    ID_MATERIAL INT PRIMARY KEY AUTO_INCREMENT,
    Titulo VARCHAR(255) NOT NULL,
    Status VARCHAR(255) NOT NULL,
    Localizacao VARCHAR(255) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_BOLSISTA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CategoriaMaterial(ID_CATEGORIA) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_BOLSISTA) REFERENCES Bolsista_Producao(ID_BOLSISTA) ON DELETE RESTRICT ON UPDATE RESTRICT,
);

-- Entidade Setor
CREATE TABLE Departamento/Setor {
	CODIGO INT PRIMARY KEY,
	Nome VARCHAR(60) NOT NULL,
	Localizacao VARCHAR(100) NOT NULL,
	Telefone VARCHAR(20) NOT NULL,
	E-mail VARCHAR (100) NOT NULL,
};

-- Entidade Cargo
CREATE TABLE Cargo {
	ID INT PRIMARY KEY, 
	Nome VARCHAR(60) NOT NULL,
};

-- Entidade Curso
CREATE TABLE Curso {
	CODIGO INT PRIMARY KEY, 
	Nome VARCHAR(50) NOT NULL, 
	Modalidade VARCHAR(20) NOT NULL,
	NivelDeFormacao VARCHAR(20) NOT NULL,
}; 

-- Atributo Funções Multivalorado de Cargo
CREATE TABLE TabelaFuncoes{
	ID_CARGO INT NOT NULL,
    Funcao VARCHAR(255), 
    CONSTRAINT ID_PERIODO PRIMARY KEY (ID_CARGO, Funcao),
	FOREIGN KEY (ID_CARGO) REFERENCES Cargo (ID) ON DELETE RESTRICT ON UPDATE CASCADE
};

-- Relacionamento Matriculado Em
CREATE TABLE MatriculadoEm {
	CPF VARCHAR(11) NOT NULL,
	Codigo INT NOT NULL, 
	Situacao VARCHAR (50),
	DataInicio DATE,
	DataFim DATE, 
	CONSTRAINT ID_Matriculado PRIMARY KEY (CPF, Codigo),
	FOREIGN KEY (CPF) REFERENCES Aluno(CPF) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (Codigo) REFERENCES Curso(Codigo) ON DELETE RESTRICT ON UPDATE CASCADE
};

-- Relacionamento Empréstimo Material
CREATE TABLE EmprestimoMaterial (
    IDPCD INT,
    IDMaterial INT,
    DataEmprestimo DATE,
    DataDevolucao DATE,
    DevolucaoEstimada DATE,
    FOREIGN KEY (IDPCD) REFERENCES PCD(ID) ON UPDATE RESTRICT,
    FOREIGN KEY (IDMaterial) REFERENCES TecnologiaEmprestavel(ID) ON UPDATE CASCADE
);


-- Relacionamento Material Disponibilizado
CREATE TABLE MaterialDisponibilizado(
    ID_PCD INT NOT NULL,
    ID_MATERIAL INT NOT NULL,
    FOREIGN KEY (ID_PCD) REFERENCES PCD(ID_PCD) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (ID_MATERIAL) REFERENCES MaterialAcessivel(ID_MATERIAL) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ID_DISPONIBILIZADO PRIMARY KEY (ID_PCD, ID_MATERIAL)
);

-- Entidade Deficiência
CREATE TABLE DadosDeficienciaPCD (
    IDPCD INT NOT NULL,
    IDDeficiencia INT NOT NULL,
    Grau VARCHAR(100),
    Observacoes TEXT,

    PRIMARY KEY (IDPCD, IDDeficiencia),

    FOREIGN KEY (IDPCD) REFERENCES PCD(ID_PCD) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (IDDeficiencia) REFERENCES Deficiencia(ID_DEFICIENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Relacionamento Presta Assistência
CREATE TABLE PrestaAssistencia (
    IDPCD INT NOT NULL,
    IDAcao INT NOT NULL,
    IDMembroCain INT NOT NULL,
    DataInicio DATE NOT NULL,
    DataFim DATE,

    PRIMARY KEY (IDPCD, IDAcao, IDMembroCain, DataInicio),

    FOREIGN KEY (IDPCD) REFERENCES PCD(ID_PCD) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (IDAcao) REFERENCES Acao(ID_ACAO) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (IDMembroCain) REFERENCES MembroDaEquipe(ID_MEMBRO_DA_EQUIPE) ON DELETE RESTRICT ON UPDATE RESTRICT
);


